spring:
  liquibase:
    enabled: true
  application:
    name: file-storage-service
  datasource:
    url: jdbc:postgresql://${PGSQL_SERVICE_HOST}:${PGSQL_SERVICE_PORT}/file_storage_db
    username: postgres
    password: ${postgres-password}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      timeout: 60000
      port: 6379
server:
  port: ${SERVICE_PORT}

topic:
  name: t.file.order

api:
  server:
    url: http://${SERVICE_HOST}:${SERVICE_PORT}
storage:
  location: http://${SERVICE_HOST}:${SERVICE_PORT}/api/storage
