spring:
  liquibase:
    enabled: false
  application:
    name: file-storage-service
  datasource:
    url: jdbc:postgresql://localhost:5430/file_storage_db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      timeout: 60000
      port: 6379
  kafka:
    consumer:
      group-id: "default"
server:
  port: 8080

topic:
  name: t.file.order

api:
  server:
    url: http://localhost:8080
storage:
  location: http://${SERVICE_HOST}:${SERVICE_PORT}/api/storage
