spring:
  application:
    name: user-service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5430/user_db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      group-id: "default"

server:
  port: 8081
topic:
  name: t.user.order

api:
  server:
    url: http://localhost:8081

jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
logging:
  level:
    org:
      springframework:
        security: TRACE